### PR TITLE
Add overview doc

### PR DESCRIPTION
**Pull request by wnbaum**
This adds a doc file that gives an overview of the flow of the program and explains the organization of the files.

Will add section for process of adding a new block.

https://phabricator.endlessm.com/T35448

### CODE REVIEW

**Comment by manuq** [comment]
Looking good! Can we just remove the deprecated stuff?

**Comment by wnbaum** [comment]
> Looking good! Can we just remove the deprecated stuff?

Yes! There was a point where it might have been useful (a sort of Picker for the "simple nodes"), but the design has since moved away from my custom scene editor idea.

**Review by dbnicholson — APPROVED** [review]
This is great! I think unless you have something you want to change right now, I'd just merge this now. It's very helpful as is and by definition it's going to need to be iterated on as we change the plugin.

**Comment by wnbaum** [comment]
Sure, sounds good!

**Pull request merged**
